### PR TITLE
add vtest.sh, so that vtest can run on Linux

### PR DESCRIPTION
**Pull request by shengofsun**
1. add vtest.sh
2. configuration -cargs splitter is changed from ";" to ","

### CODE REVIEW

**Comment by imzhenyu** [comment]
why chang ; to , ? we have many comments and shell scripts (both windows and Linux) that use ; already. You may search cargs for the usages and comments in C++.

**Comment by shengofsun** [comment]
Well, ";" doesn't work on linux. Should I add a macro to treat windows and linux differently?

**Comment by shengofsun** [comment]
Or let me modify the code, to make both ";" and "," works.

**Comment by imzhenyu** [comment]
Thanks @shengofsun . Why does Linux not support ';' ? :)

**Comment by shengofsun** [comment]
";" will be treated as the end of a command in linux shell interpretor. It will be ok if using a escape character "\". But this is a little weird, and I think we should avoid using the special characters of shell.

**Comment by imzhenyu** [comment]
I see. Thx.

**Comment by imzhenyu** [comment]
[0;31m[  FAILED  ] [m2 tests, listed below:
[0;31m[  FAILED  ] [mfd.old_master_died
[0;31m[  FAILED  ] [mfd.worker_died_when_switch_master

Any status about these cases?

**Comment by shengofsun** [comment]
I'm checking this, and I'm running this case on my PC. Zuoyan merged it because other members needs the vtest.sh to run vtest, and this fix should have nothing to do with the FD test.

**Comment by imzhenyu** [comment]
Understand - you may fire issues if this is found new.

**Pull request merged**
