### PR TITLE
add sample perf counters in replication, and fix some bugs 

### PR DESCRIPTION
**Pull request by imzhenyu**
see details in commit logs. 

TODO: more counters in replica, meta, network, rpc, disk, computation engine, etc.

### CODE REVIEW

**Comment by imzhenyu** [comment]
bugs found in percentile counters, to be fixed

**Comment by imzhenyu** [comment]
@glglwty please help review. and you may add more counters on demand in network/rpc/disk/thread-pool/meta server etc. when you do the profiling.

**Comment by glglwty** [comment]
I still don't know why we should use ref_ptr.

**Comment by imzhenyu** [comment]
check-out here : https://github.com/imzhenyu/rDSN/blob/imzhenyu/src/core/core/perf_counters.cpp#L222. The counter is used outside the lock scope, which could happen after we remove the lock, which is dangerous.

**Comment by imzhenyu** [comment]
https://github.com/imzhenyu/rDSN/commit/c9f2abd855e992978a13aacd78fe15d8a80594af @qinzuoyan the reference count is not guaranteed to be decreased in worker thread as they are parallel. But we do be able to check this in simulation mode.

**Comment by imzhenyu** [comment]
Because in simulator, a task is atomic (well, there are exceptions, but not the case here).

**Comment by imzhenyu** [comment]
Seems wrong scripts lead to the travis failure above. I'm going to merge this now.

4186    +  state:{{r1,pri,3,0},{r2,sec,3,0},{r3,sec,3,0}}

4187   13  inject:on_rpc_call:rpc_name=RPC_LEARN_ADD_LEARNER,from=r1,to=r2

4188 <==>  null_loop:10000

4189run case-102 failed, return value = 255

4190ERROR: run dsn.rep_tests.simple_kv failed

**Pull request merged**
