### PR TITLE
bug fix when learnee's mutations ballot are the same with learner's

### PR DESCRIPTION
**Pull request by shengofsun**
@imzhenyu 
This fix is related to issue #496 and pr #498 , due to my bad, ballot compare should be ">" but not ">="

### CODE REVIEW

**Comment by imzhenyu** [comment]
@shengofsun I think equal is ok, what is your case that makes it inappropriate?

**Comment by shengofsun** [comment]
@imzhenyu when a existing mutation and a coming mutation from learnee are same ballot, the existing one is not necessarily logged, which will make the later assertion failed in later commit.

**Comment by shengofsun** [comment]
@imzhenyu I have just realized that even the existing mutation is with larger ballot, it is not necessarily logged, so do you have any suggestions?

**Comment by imzhenyu** [comment]
The filter is only applied to prepare, and we always log them as we truncate the log before learning.

**Comment by imzhenyu** [comment]
So the question is the old mutations may not be logged yet (though with the same content with the new logged mutations). This pr fixed this issue.

**Pull request merged**
