### PR TITLE
fix mutation log write bug, and add test case

### LINKED ISSUE #175: latency in shared mutation log
# problem

Currently in shared mutation_log, an append operation would dispatch a file::write if is_writing is false. For shared log, if it is delayed by is_writing and then the replica stopped doing init_prepare task, the shared log might never be written to the disk.
# possible fix

Bypass all the issued_write, pending_write stuff for shared log.
# discussion

The behavior of shared log and private log differs a lot. We could consider taking them apart into separate classes.

### PR DESCRIPTION
**Pull request by qinzuoyan**
for fix #175

### CODE REVIEW

**Comment by imzhenyu** [comment]
@glglwty please help review

**Comment by glglwty** [comment]
It looks good and should fix the problem. But actually we can bypass all the issued_write stuffs for shared_log and write through at every append(). Issued_write, as well as the flush() in internal_write_callback, is to make sure that there is no gap in private log and in-memory buffer so that we can get all the mutations in the learning process. (If there is a gap between private log and in-memory buffer, the learner might end up with a corrupted state because the learner might not sense the gap if there is a ballot change within it. That's another story.) So issued_write and flush() have nothing to do with shard log. Compared to this fix, removing the issued_write stuffs for shared log could enhance the performance.

**Comment by imzhenyu** [comment]
Agree with @glglwty . One other story is that let's keep flushing and batching as two separated flags for mutation log, which has nothing to do with being shared or private. In current case, we can set flush = false, batch = 0 for shared log, and flush = true, batch > 0 for private log. We may have other configurations in the future (e.g., combined shared and private log for one-replica-per-server setting).

**Comment by qinzuoyan** [comment]
@imzhenyu @glglwty , I have improve the mutation_log to add log_shared_force_flush/log_private_force_flush options.
Let's leave refactor of separating mutation_log to two different classes for private and shared to the future.

**Comment by imzhenyu** [comment]
Seems good to me now.

**Pull request merged**
