### PR TITLE
  fix learning failure exposed by failure injection 

### PR DESCRIPTION
**Pull request by imzhenyu**
among other nits

### CODE REVIEW

**Comment by imzhenyu** [comment]
@qinzuoyan  here is a serious bug about learning, please take a look: 

https://github.com/imzhenyu/rDSN/pull/392/commits/6aa11dea4ef298b5df9726d8179623f34c360055

**Comment by qinzuoyan** [comment]
why reopen it?

**Comment by imzhenyu** [comment]
there are several .act tests not passed before, and now they are fine:-) Some of the flows defined in the act files are not true any more.

**Comment by qinzuoyan** [comment]
OK, now the master branch is stable enough for merging our codes?

**Comment by imzhenyu** [comment]
Sure, please go ahead. I've tried to merge some though (e.g., https://github.com/imzhenyu/rDSN/pull/392/commits/834082afa00bd6b041fc21917e1fbc903b12ebbe), and it is not easy (I've tried cherry-pick but in the end it is almost by manually incorporating every changes). Wish you guys good luck~

**Pull request merged**
