### PR TITLE
Serialization

### PR DESCRIPTION
**Pull request by shengofsun**
1. refactor on the serialization. 
2. add a "type" field in message_header, may be useful for multiple rpc header parser.

### CODE REVIEW

**Comment by imzhenyu** [comment]
@shengofsun Thanks. About the new type member in message_header, it is best we can reuse the context filed to not increase the message header size. @ykwd has already come up a sort of complete implementation with various format types (binary/Json x thrift/protoc) supported simultaneously. I'm wondering whether we can simply skip commit 4a46eb2 at this time, and adopting the later commit from @ykwd next week. Thanks.

**Comment by shengofsun** [comment]
No problem @imzhenyu @ykwd

**Comment by shengofsun** [comment]
@imzhenyu there are some other issues on the message_header:
(1) currently the message_header is sent by the raw memory layout of the "struct message_header", which is not a good practice if concerning the compiler's memory align and the network byte order. After all, we may want our RPC to support multiple language/OS platforms, and even multiple 
architectures.
(2) I'd prefer the message type be the first field in a message, so that other protocols may have their own message header.
(3) Currently the message_header is not extensible. For example, what if I want to add a new field in the message_header? So what about adding a new field "body_offset"?

**Comment by imzhenyu** [comment]
@shengofsun Thanks and these are great questions. Here are some short answers, and we can discuss them in more details in the future.
(1). `sent by memcpy` is mostly for performance considerations. For fields that may have different byte orders, we can explicitly ask developers to convert these fields before sent, so that the format is consistent on network (e.g., in network byte order). For memory alignment, we can use compiler pragmas which are standardized. 
(2). Good suggestion. We may have the current `magic` filed moved to the first and serve this purpose. I'm not sure whether each protocols we care have such magic number though. Currently, we have separated listen port for each of different message header parsers (e.g., dsn, thrift, http). 
(3). Good suggestion. When we have a concrete requirement, let's do that:)

**Comment by imzhenyu** [comment]
@shengofsun @qinzuoyan @xiaotz I've added a new branch called `v0.95` for your usage.

**Comment by ykwd** [comment]
@shengofsun  If(DSN_GIT_SOURCE STREQUAL "xiaomi") then it will get some external project source code from git.n.xiaomi.com. Since this git is not available outside xiaomi company, I'm not sure if other users would confuse about this.

**Comment by qinzuoyan** [comment]
@ykwd , the xiaomi git source is just for our internal use, and other users should not use it.

**Comment by qinzuoyan** [comment]
@imzhenyu , please also add a new branch called v0.95 for imzhenyu/rocksdb :)

**Comment by imzhenyu** [comment]
@qinzuoyan sure~

**Comment by imzhenyu** [comment]
@qinzuoyan done, please check.

**Comment by qinzuoyan** [comment]
@imzhenyu , I have seen it, thanks.

**Pull request merged**
