### PR TITLE
add research papers for reference 

### PR DESCRIPTION
**Pull request by imzhenyu**
so people can get better understanding about rDSN

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , Is you paper accepted by OSDI finally?

**Comment by imzhenyu** [comment]
bad news unfortunately~

**Comment by qinzuoyan** [comment]
Sorry to hear that, but it is really a difficult task. Just go ahead for
other conferences, good news will come soon.

**Comment by imzhenyu** [comment]
I'm confident about our work, and it is mostly about writing. Will work for a while first before trying the next:)

**Pull request merged**
