### PR TITLE
test framework restructure 

### PR DESCRIPTION
**Pull request by imzhenyu**
- move dsn.core.test and dsn.core.perf.test into dsn modules, using [core] gtest = true and [core] gtest_arguments = --gtest_filter=xxx for running certain test cases
- refine upmost test for auto test using run.sh/.cmd, which searches and runs the following two kinds of tests
  - build_dir/test/proj_name/gtests for automatic unit test (see core, tools.common, and tools.hpc for examples)
  - build_dir/bin/proj_name/test.sh/cmd for automatic tests as specified by test.sh/.cmd

### CODE REVIEW

**Comment by imzhenyu** [comment]
@qinzuoyan I've done some major changes; please take a look to ensure that Pegasus won't be broken (which I think so). The next step will be moving some components into separated repos.

**Comment by qinzuoyan** [comment]
looks good to me, and I have tested rrdb successfully.

**Comment by imzhenyu** [comment]
That's great, thx.

**Comment by qinzuoyan** [comment]
@imzhenyu , now [rocksdb/rdsn-intrusive](https://github.com/imzhenyu/rocksdb/tree/rdsn-instrusive) has been upgraded to be compatible with this pr.

**Pull request merged**
