### PR TITLE
fix dsn_mimic_app() usage  &  remove useless app_name in config.ini

### PR DESCRIPTION
**Pull request by qinzuoyan**
- fix dsn_mimic_app() usage in zookeeper_session::init_non_dsn_thread
- remove useless app_name in config.ini

### CODE REVIEW

**Comment by imzhenyu** [comment]
Zuoyan, I'm afraid your understand about app name for mimic_app is incorrect. In certain cases, it is possible we have multiple sections of [apps.xxx] with the same app_type, simply because the app instances may require different parameters. As a result, we are using app_name for mimic instead of app role.

**Comment by qinzuoyan** [comment]
But the name in config.ini is never used, so there are still some problems.

And event it is possible we have multiple sections of [apps.xxx] with the same app_type, the role name can be different. e.g.:
[apps.rep1]
type = rep_impl
count = 2

[apps.rep2]
type = rep_impl
count = 3

so we can combine the role_name and app_name in config to role_name, and we refer app_name internally as app full name in format if ${role_name}${role_index}.

**Comment by qinzuoyan** [comment]
I have standard the terms used in rDSN, you can see the doc in struct service_app_spec.
Terms include:
- app_id
- app_name/role_name
- role_index
- app_full_name
- app_type

**Comment by qinzuoyan** [comment]
resolved in https://github.com/baidu/sofa-pbrpc/issues/40

**Comment by imzhenyu** [comment]
great, but the compilation test seems not passed as shown above?

**Comment by qinzuoyan** [comment]
this is caused by linkage problem of zookeeper:

```
/home/travis/build/imzhenyu/rDSN/builder/zookeeper-lib/libzookeeper_mt.a(zk_log.c.o): In function `time_now':
zk_log.c:(.text+0x1f5): undefined reference to `snprintf_z'
collect2: error: ld returned 1 exit status
```

fixed in https://github.com/shengofsun/zookeeper_client_c/commit/7db55b874f9670c55b165f981a22dc226d5e1a0c https://github.com/shengofsun/zookeeper_client_c/commit/3de29dd6e53867df4182b9cbda75aa158910e2c3 https://github.com/shengofsun/zookeeper_client_c/commit/9970b9aa2e1ec4083f74a32043785d460a1e7003

**Comment by imzhenyu** [comment]
got you. merge now.

**Pull request merged**
