### PR TITLE
split hash to thread_hash and partition_hash, refer to #508

### PR DESCRIPTION
**Pull request by qinzuoyan**
and work together with https://github.com/imzhenyu/rDSN.dist.deployment/pull/2

### CODE REVIEW

**Comment by qinzuoyan** [comment]
@imzhenyu , please review it. 

And dsn_gpid_to_hash() has also been changed to dsn_gpid_to_thread_hash().

**Comment by qinzuoyan** [comment]
The ci test failed because https://github.com/imzhenyu/rDSN.dist.deployment/pull/2 not commited

**Comment by imzhenyu** [comment]
Merged, and You may git submodule update --remote and try again

**Comment by qinzuoyan** [comment]
@imzhenyu , can this pr be merged now?

**Pull request merged**
