### PR TITLE
fix on meta_server

### PR DESCRIPTION
**Pull request by shengofsun**
1. store to meta_state_service with json
2. add query_cache api in dist_lock
3. modify meta_server_failure_detector, response ping message when not leader
4. other small fixes

implements https://github.com/imzhenyu/rDSN/issues/47 https://github.com/imzhenyu/rDSN/issues/125

### CODE REVIEW

**Comment by shengofsun** [comment]
@imzhenyu bug fix according to your comments yesterday. I agree that the Tianyi's json lib is much better. But there is no decoding api in that lib. Besides, it's not very convenient to use if I only want to encode parts of a struct. If necessary, let's replace the rapidjson later. 
In addition, I modified the meta_server_failure_detector. It isn't a strictly perfect FD now. When a master is initializing, a non-registered worker in master may also regard itself alive. But I think this shouldn't influence the correctness, because in this case the master can't assign new tasks for replica-server. 
Anyway, we should consider this carefully. @imzhenyu @qinzuoyan

**Comment by imzhenyu** [comment]
Got what you mean now after reading the code change, please ignore this message. --------------- I see you have active_xxx() method which will prevent the workers being registered during the period when the server is still syncing with ZK. So your mentioned issue is already fixed. Anything that I've mistaken here?

**Comment by shengofsun** [comment]
After I recheck the code, I think r->_stub->is_connected() is enough. And I indeed encounter this assertion failed. So perhaps some bugs exist, which I haven't found it yet T_T

**Comment by imzhenyu** [comment]
Your meta master does not register the worker during init, so they should be considered dead. However, the workers do receive the acks to avoid unnecessary fail=over, so they are alive. In this case, the meta master is in non-active mode. So || !r->_stub->is_activated() ?

**Comment by shengofsun** [comment]
I c. So you mean we need to add a member function replica_stub::is_activated()?
And the meaning of the member function is that all replicas in this stub is PS_INACTIVE or PS_ERROR?
Have a talk on slack?

**Comment by imzhenyu** [comment]
sorry, should be meta_fd::is_activated() instead of stub->is-activated()

**Comment by shengofsun** [comment]
@imzhenyu , I've fixed the meta_service_failure_detector to make it a perfect FD, please help review.

**Comment by imzhenyu** [comment]
looks great, merged now.

**Pull request merged**
