### PR TITLE
add separated timer for beacon send in FD

### PR DESCRIPTION
**Pull request by imzhenyu**
(1) add separated timer for beacon send in FD
(2) refine deployment scripts on windows

### CODE REVIEW

**Comment by imzhenyu** [comment]
@shengofsun  please help review.

**Comment by imzhenyu** [comment]
@shengofsun note the FD notes are refined - zookeeper related notes are deleted and please move them somewhere else e.g., meta server fd, which is more appropriate.

**Comment by shengofsun** [comment]
The fix seems fine to me. I'll check the reason for the FD test failure tomorrow :-)

**Comment by imzhenyu** [comment]
Good. The original code passes the test, but it also has problems that easily lead to coredump using simplekv.vtest.cmd at line 602 in replica_config.cpp "invalid execution path" - seems to be caused by perfect FD invariance violation. Please check that issue as well.

**Comment by imzhenyu** [comment]
The failure above is not related to the changes in this pr, merge now.

**Pull request merged**
