### PR TITLE
refactor thrift serialization's compilation & add support for rpc with thrift

### PR DESCRIPTION
**Pull request by shengofsun**
1. Fix thrift's compilation, currently the thrift library is compiled to a dynamic library on Linux. More works need to be done on Windows.
2. The cmake option "DSN_SERIALIZATION_TYPE" is used to control the serialization method of rDSN. On Linux "thrift" and "dsn" is supported, and on windows currently only "dsn" is supported.
3. Add serialization type option in "run.sh". For example, "./run.sh build -s thrift" will build the system with thrift serialization.
4. Modify the message_parser to support the thrift header parser. Thus we can write replication client with other language.

### CODE REVIEW

**Comment by shengofsun** [comment]
@imzhenyu now the code serialization part and rpc part has been refactored according to our meeting yesterday. Now the thrift lib is still downloaded from my github repo. If no other problems, I will fix this in later pr.

**Comment by imzhenyu** [comment]
Thanks, Weijie. I'm afraid I still have some issues with this change. Let's discuss it next week when we meet face to face.

**Comment by shengofsun** [comment]
OK

**Comment by ykwd** [comment]
@shengofsun  now the lib of thrift is compiled locally on branch layer3. I will merge it to master branch after this pr. 
ps : the check failed on appveyor

**Comment by shengofsun** [comment]
@ykwd thank you. I'm working on this.

**Pull request closed without merging**
